plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.shelfplayer'
    compileSdk 36

    defaultConfig {
        applicationId 'com.example.shelfplayer'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.media3:media3-exoplayer:1.11.0'
    implementation 'androidx.media3:media3-session:1.11.0'
}
